"""add announcement blocks

Revision ID: 19005eb028ad
Revises: b3e380bae4f5
Create Date: 2026-08-22 16:59:38.625685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '19005eb028ad'
down_revision: Union[str, Sequence[str], None] = 'b3e380bae4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('block', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id', 'announcement_id', 'block')
    )
    op.create_index(op.f('ix_announcement_blocks_block'), 'announcement_blocks', ['block'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcement_blocks_block'), table_name='announcement_blocks')
    op.drop_table('announcement_blocks')
    # ### end Alembic commands ###
