"""add complaint table

Revision ID: a930099bb9ea
Revises: 9b888b3c4d75
Create Date: 2026-08-07 18:49:01.465532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a930099bb9ea'
down_revision: Union[str, Sequence[str], None] = '9b888b3c4d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRICAL', 'PLUMBING', 'INTERNET', 'CLEANING', 'FURNITURE', 'WATER', 'MESS', 'OTHER', name='complaintcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaintpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaintstatus'), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('reported_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_title'), 'complaints', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_title'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
