"""add block to rooms

Revision ID: e9e11ab187cb
Revises: 6eac5e948c58
Create Date: 2026-08-09 18:43:24.104282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'e9e11ab187cb'
down_revision: Union[str, Sequence[str], None] = '6eac5e948c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('block', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('rooms', sa.Column('room_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.create_index(op.f('ix_rooms_block'), 'rooms', ['block'], unique=False)
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rooms_block'), table_name='rooms')
    op.drop_column('rooms', 'room_number')
    op.drop_column('rooms', 'block')
    # ### end Alembic commands ###
